import { ROLES } from "./roles";
import { PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS = {
  [ROLES.INDIVIDUAL]: [
    PERMISSIONS.QUEST_VIEW,
    PERMISSIONS.QUEST_APPLY,
    PERMISSIONS.PROPOSAL_VIEW,
    PERMISSIONS.PROPOSAL_CREATE,
    PERMISSIONS.PROPOSAL_UPDATE,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.VERIFICATION_SUBMIT,
    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.PAYOUT_REQUEST,
    PERMISSIONS.PARTY_CREATE,
    PERMISSIONS.PARTY_MANAGE,
  ],
  [ROLES.CLIENT]: [
    PERMISSIONS.QUEST_VIEW,
    PERMISSIONS.QUEST_CREATE,
    PERMISSIONS.QUEST_UPDATE,
    PERMISSIONS.QUEST_DELETE,
    PERMISSIONS.PROPOSAL_VIEW,
    PERMISSIONS.PROPOSAL_ACCEPT,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.VERIFICATION_SUBMIT,
    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.PAYMENT_MANAGE,
  ],
  [ROLES.AGENCY]: [
    PERMISSIONS.QUEST_VIEW,
    PERMISSIONS.QUEST_CREATE,
    PERMISSIONS.QUEST_APPLY,
    PERMISSIONS.PROPOSAL_VIEW,
    PERMISSIONS.PROPOSAL_CREATE,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.TEAM_MANAGE,
    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.PAYOUT_REQUEST,
    PERMISSIONS.VERIFICATION_SUBMIT,
  ],
  [ROLES.ADMIN]: [
    ...Object.values(PERMISSIONS),
  ],
};
